In [ ]:
https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

df = pd.read_csv(url)

df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

In [9]:
#LIMPIEZA DE DATOS
polizas = df.copy()

polizas.columns = polizas.columns.str.strip().str.lower()

for col in polizas.select_dtypes(include='object').columns: polizas[col] = polizas[col].astype(str).str.strip()

polizas = polizas.replace(r'^\s*$', pd.NA, regex=True)

polizas['fecha_emision'] = pd.to_datetime(polizas['fecha_emision'], errors='coerce')
polizas['prima'] = pd.to_numeric(polizas['prima'], errors='coerce')
polizas['comision'] = pd.to_numeric(polizas['comision'], errors='coerce')
polizas['monto_asegurado'] = pd.to_numeric(polizas['monto_asegurado'], errors='coerce')

polizas = polizas.drop_duplicates()

In [11]:
#SEPARAR DATOS VALIDOS Y RECHAZADOS
validos = polizas[
    polizas['fecha_emision'].notna() &
    polizas['prima'].notna() &
    polizas['comision'].notna()
].copy()

rechazados = polizas[
    polizas['fecha_emision'].notna() &
    polizas['prima'].notna() &
    polizas['comision'].notna()
].copy()

In [12]:
#CREA FILA MOTIVO DE RECHAZO
def motivo(row):

    motivos = []

    if pd.isna(row['fecha_emision']):
        motivos.append("fecha_vacio")

    if pd.isna(row['prima']):
        motivos.append("prima_vacio")

    if pd.isna(row['comision']):
        motivos.append("comision_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [13]:
#EXPORTACIÓN DE ARCHIVOS --> ENVIAR A RECHAZADOS O VALIDOS
validos.to_csv("polizas_curated.csv", index=False)

rechazados.to_csv("polizas_rejects.csv", index=False)

In [14]:
#
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_agnz_user:0NeQE82pEYWiuecWGeGciNE7aO4ev1F1@dpg-d6qu6o9j16oc73eu7250-a.oregon-postgres.render.com/etl_seguros_agnz"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 71.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [15]:
#CARGAR DATOS EN POSTGRESQL
validos.to_sql(
    'polizas_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'polizas_rejects',
    engine,
    if_exists='append',
    index=False
)

411

In [16]:
#VALIDAR LA CARGA

pd.read_sql(
"SELECT * FROM polizas_curated LIMIT 10",
engine
)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,NaN,NaN,139253.11
1,4,NaT,2821,40,10,5,1866.62,456.99,244461.27
2,5,NaT,945,23,9,11,NaN,NaN,123407.75
3,6,NaT,1295,17,1,1,943.49,NaN,71968.43
4,7,NaT,1254,25,11,4,1400.82,188.40,258202.93
5,9,NaT,1670,66,8,12,NaN,NaN,125804.84
6,10,2026-01-24,2281,69,13,3,791.38,NaN,20710.00
7,12,NaT,1521,14,11,5,726.02,NaN,86216.65
8,14,NaT,367,65,1,11,0.00,122.12,249504.31
9,17,NaT,856,73,14,8,832.85,NaN,94675.98