https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv

In [2]:
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"

df = pd.read_csv(url)

df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [4]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

In [30]:
#limpieza de datos
siniestros = df.copy()

siniestros.columns = siniestros.columns.str.strip().str.lower()

for col in siniestros.select_dtypes(include='object').columns: siniestros[col] = siniestros[col].astype(str).str.strip()

siniestros = siniestros.replace(r'^\s*$', pd.NA, regex=True)

siniestros['estado'] = siniestros['estado'].str.lower()

siniestros['monto_siniestro'] = pd.to_numeric(siniestros['monto_siniestro'], errors='coerce')

siniestros['fecha_siniestro'] = pd.to_datetime(siniestros['fecha_siniestro'], errors='coerce',
    dayfirst=True)

siniestros = siniestros.drop_duplicates()

In [23]:
#SEPARAR DATOS VALIDOS Y RECHAZADOS
validos = siniestros[
    siniestros['estado'].notna() &
    siniestros['monto_siniestro'].notna()
].copy()

rechazados = siniestros[
    siniestros['estado'].isna() &
    siniestros['monto_siniestro'].isna()
].copy()

In [24]:
#CREA FILA MOTIVO DE RECHAZO
def motivo(row):

    motivos = []

    if pd.isna(row['estado']):
        motivos.append("estado_vacio")

    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [25]:
#EXPORTACIÓN DE ARCHIVOS --> ENVIAR A RECHAZADOS O VALIDOS
validos.to_csv("siniestros_curated.csv", index=False)

rechazados.to_csv("siniestros_rejects.csv", index=False)

In [26]:
#
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_agnz_user:0NeQE82pEYWiuecWGeGciNE7aO4ev1F1@dpg-d6qu6o9j16oc73eu7250-a.oregon-postgres.render.com/etl_seguros_agnz"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [27]:
#CARGAR DATOS EN POSTGRESQL
validos.to_sql(
    'siniestros_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'siniestros_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [28]:
#VALIDAR LA CARGA

pd.read_sql(
"SELECT * FROM siniestros_curated LIMIT 10",
engine
)

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      16-10-2025          2092.59    abierto
1             3      15785      19-09-2025           702.27    cerrado
2             4      14299      27/09/2025           274.63    abierto
3             8      23824      17-01-2025          2736.20    abierto
4            10      19947      2025/09/12          8801.03    cerrado
5            13       3716      13-07-2025         -4274.39  rechazado
6            15      19142      2025/01/29         14533.77    abierto
7            19       5547      2025-10-10          5714.06    cerrado
8            20      21508        08-29-25          8867.02        nan
9            22       6924      16/11/2025         10436.86    cerrado