https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"

df = pd.read_csv(url)

df.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

id_tipo_seguro    0
tipo              0
categoria         2
riesgo_base       2
dtype: int64

In [4]:
#limpieza de datos
tipos_seguro = df.copy()

tipos_seguro.columns = tipos_seguro.columns.str.strip().str.lower()

for col in tipos_seguro.select_dtypes(include='object').columns: tipos_seguro[col] = tipos_seguro[col].astype(str).str.strip()

tipos_seguro = tipos_seguro.replace(r'^\s*$', pd.NA, regex=True)

tipos_seguro['categoria'] = tipos_seguro['categoria'].str.lower()

tipos_seguro['riesgo_base'] = pd.to_numeric(tipos_seguro['riesgo_base'], errors='coerce')

tipos_seguro = tipos_seguro.drop_duplicates()

In [5]:
#SEPARAR DATOS VALIDOS Y RECHAZADOS
validos = tipos_seguro[
    tipos_seguro['categoria'].notna() &
    tipos_seguro['riesgo_base'].notna()
].copy()

rechazados = tipos_seguro[
    tipos_seguro['categoria'].isna() &
    tipos_seguro['riesgo_base'].isna()
].copy()

In [6]:
#CREA FILA MOTIVO DE RECHAZO
def motivo(row):

    motivos = []

    if pd.isna(row['categoria']):
        motivos.append("categoria_vacio")

    if pd.isna(row['riesgo_base']):
        motivos.append("riesgo_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [7]:
#EXPORTACIÓN DE ARCHIVOS --> ENVIAR A RECHAZADOS O VALIDOS
validos.to_csv("tipos_seguros_curated.csv", index=False)

rechazados.to_csv("tipos_seguros_rejects.csv", index=False)

In [8]:
#
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_agnz_user:0NeQE82pEYWiuecWGeGciNE7aO4ev1F1@dpg-d6qu6o9j16oc73eu7250-a.oregon-postgres.render.com/etl_seguros_agnz"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 42.2 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [9]:
#CARGAR DATOS EN POSTGRESQL
validos.to_sql(
    'tipos_seguros_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'tipos_seguros_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [10]:
#VALIDAR LA CARGA

pd.read_sql(
"SELECT * FROM tipos_seguros_curated LIMIT 10",
engine
)

   id_tipo_seguro        tipo    categoria  riesgo_base
0               2  Industrial  empresarial         4.68
1               3  Industrial     familiar         5.10
2               5        Auto  empresarial         9.07
3               6  Industrial  empresarial         2.52
4               7       Salud     personal         0.92
5               8   Educación  empresarial         7.42
6               9  Accidentes          nan         5.68
7              10      Dental     especial         2.70
8              11        Auto  empresarial         4.33